### PR TITLE
screenshots: Update screenshots for Grml release 2024.12

### PR DESCRIPTION
**Pull request by jkirk**
Screenshots were taken via QEMU Monitor, i.e:

```
  (qemu) screendump bootsplash_efi.png -f png
```

The screenshot thumbnails were created with:

```
  % for i in booting.jpg bootsplash_efi.png console.png grml_2024.12.png vesamenu.png ; convert "$i" -resize 250x "${i%.png}.jpg"
```
grml-info defaults to links2 in framebuffer mode nowadays, updated the description. Also see: grml/grml-scripts#22

### CODE REVIEW

**Review by mika — APPROVED** [review]
Love it, thanks! :heart:  :grin:

**Comment by jkirk** [comment]
@mika FTR: The fluxbox link points to https://sourceforge.net/projects/fluxbox/. This seems to be the official homepage: http://fluxbox.org/ (note, its currently http only, but seems up to date). Should we change that?

**Comment by mika** [comment]
> @mika FTR: The fluxbox link points to https://sourceforge.net/projects/fluxbox/. This seems to be the official homepage: http://fluxbox.org/ (note, its currently http only, but seems up to date). Should we change that?

yeah sounds like a good idea, thx!

**Review by mika — APPROVED** [review]

**Comment by mika** [comment]
Thanks @jkirk! Cherry-picked to https://github.com/grml/grml.org/pull/69

**Pull request closed without merging**
