### PR TITLE
Use hugo

### PR DESCRIPTION
**Pull request by zeha**
TODO:
- [x] convert remaining files (changelogs/*) to md
- [x] determine how /tips/ should look like
- [x] rewrite download/mirrors to use github data
- [x] build using gh action
- [x] deployment?
- [x] deployment: restrict to master branch

fyi @mika

### CODE REVIEW

**Comment by zeha** [comment]
@mika /tips/ currently has a yellow background. Do we care about that, or is white fine?

**Comment by mika** [comment]
> @mika /tips/ currently has a yellow background. Do we care about that, or is white fine? Not sure if there will be other differences, most stuff is in `\<pre\>` blocks anyway.

IMO we don't need the yellow background, white is perfectly fine IMO :)

**Comment by zeha** [comment]
The only other thing to figure out is how to get the built files onto the web VM.
My only ideas so far:
1) have gh-actions ssh (don't want to store a key here)
2) have gh-actions call some http URL (cgi?)
3) use a cronjob to poll for new artifacts
4) ?

**Comment by zeha** [comment]
I've written deployment tooling and deployed this branch.

**Comment by zeha** [comment]
I'm going to merge this so I can deploy a few fixes. If you find time, please still check this PR out :)

**Pull request merged**
